apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: #this labels are deployment labels
    app: shipping
    project: roboshop
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels: #this labels are used to find the pods
      app: shipping
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: "pavan49r/shipping:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping