apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels: #this labels are deployment labels
    app: catalogue
    project: roboshop
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels: #this labels are used to find the pods
      app: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: pavan49r/catalogue:{{ .Values.deployment.imageVersion}}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue